begin;
set local app.allow_legacy_alpha_testers='on';
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(22);
select has_table('public','founder_point_history','FP history exists');
select has_table('public','achievement_claims','achievement claims exist');
select has_table('public','player_daily_orders','daily order persistence exists');
select has_table('public','action_telemetry','action telemetry exists');
select has_table('public','abuse_signals','anti-abuse signals exist');
select has_view('public','daily_economy_metrics','economy aggregate exists');
select has_function('public','claim_daily_quest',array['text','uuid'],'daily claim RPC exists');
select has_function('public','claim_weekly_streak',array['uuid'],'weekly claim RPC exists');
select has_function('public','claim_achievement',array['text','uuid'],'achievement RPC exists');
select has_function('public','get_admin_economy_dashboard',array[]::text[],'admin dashboard RPC exists');
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token)values('00000000-0000-0000-0000-000000000000','66666666-6666-4666-8666-666666666666','authenticated','authenticated','m5@example.test',crypt('password',gen_salt('bf')),now(),'{}','{"username":"RetentionTester"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claim.sub','66666666-6666-4666-8666-666666666666',true);
select lives_ok($$select public.get_player_game_state()$$,'state load creates daily state');
select is((select count(*) from public.player_quests where player_id=auth.uid() and quest_date=current_date),4::bigint,'four daily quests persist');
select is((select count(*) from public.player_daily_orders where player_id=auth.uid() and order_date=current_date),3::bigint,'three daily orders persist');
select lives_ok($$select public.get_player_game_state()$$,'reload does not reroll');
select is((select count(distinct order_id) from public.player_daily_orders where player_id=auth.uid() and order_date=current_date),3::bigint,'daily orders are unique');
select throws_like($$select public.claim_daily_quest('daily-jobs-3','60000000-0000-4000-8000-000000000001')$$,'%not complete%','incomplete quest cannot claim');
select throws_like($$select public.claim_achievement('first_shift','60000000-0000-4000-8000-000000000002')$$,'%not unlocked%','locked achievement cannot claim');
select throws_like($$select public.get_admin_economy_dashboard()$$,'%ADMIN_REQUIRED%','ordinary player cannot access admin dashboard');
select is((select count(*) from public.founder_point_history where player_id=auth.uid()),0::bigint,'FP history begins empty');
select is((select count(*) from public.profiles where id<>auth.uid()),0::bigint,'cross-player profiles hidden by RLS');
reset role;update public.residents set jobs_completed=1 where player_id='66666666-6666-4666-8666-666666666666';set local role authenticated;select set_config('request.jwt.claim.sub','66666666-6666-4666-8666-666666666666',true);
select lives_ok($$select public.claim_achievement('first_shift','60000000-0000-4000-8000-000000000003')$$,'eligible achievement claims');
select throws_like($$select public.claim_achievement('first_shift','60000000-0000-4000-8000-000000000004')$$,'%already claimed%','achievement cannot claim twice');
select * from finish();rollback;
