import { CheckCircle2, Home, LockKeyhole } from 'lucide-react';
import { ECONOMY } from '../../config/economy';
import { useGameStore } from '../../stores/gameStore';
import { PanelHeader } from '../inventory/InventoryPanel';

export function PropertyPanel() {
  const player=useGameStore((state)=>state.player); const authenticated=useGameStore((state)=>state.authenticated); const setPanel=useGameStore((state)=>state.setPanel); const upgrade=useGameStore((state)=>state.upgradeProperty); const fund=useGameStore((state)=>state.fundPropertyUpgrade); const pending=useGameStore((state)=>state.actionPending); if(!player) return null;
  const level=player.property.level as 1|2|3; const current=ECONOMY.property[level]; const target=level<3 ? (level+1) as 2|3 : null; const next=target ? ECONOMY.property[target] : null; const atHome=player.resident.currentLocation==='home';
  const progress=player.property.upgradeProgress; const reserved=progress.targetLevel===target?progress:{targetLevel:null,wood:0,stone:0,iron:0};
  const hasRequirements=!authenticated||(next ? player.economy.coins>=next.cost.coins&&player.inventory.wood+reserved.wood>=next.cost.wood&&player.inventory.stone+reserved.stone>=next.cost.stone&&('iron' in next.cost?player.inventory.iron+reserved.iron>=next.cost.iron:true) : false);
  const canReserve=!authenticated||(next ? player.inventory.wood>0&&reserved.wood<next.cost.wood||player.inventory.stone>0&&reserved.stone<next.cost.stone||'iron' in next.cost&&player.inventory.iron>0&&reserved.iron<next.cost.iron : false);
  return <section className="panel"><PanelHeader title="Your Property" onClose={()=>setPanel('world')}/><div className="grid gap-4 sm:grid-cols-[.8fr_1.2fr]"><div className={`grid min-h-48 place-items-center rounded-2xl property-tier-${level}`}><div className="text-center text-white drop-shadow"><Home className={`mx-auto ${level===3?'h-20 w-20':level===2?'h-16 w-16':'h-12 w-12'}`}/><p className="mt-2 font-display text-xl font-bold">{current.name}</p><p className="text-sm">Level {level}</p></div></div><div><div className="grid grid-cols-3 gap-2">{[['Storage',`${player.property.storageUsed}/${player.property.storageCapacity}`],['Residents',player.property.residentCapacity],['Business slots',player.property.businessSlots]].map(([label,value])=><div key={label} className="rounded-xl bg-white p-3 text-center"><p className="text-xs text-ink/45">{label}</p><b>{value}</b></div>)}</div>{next&&target?<div className="mt-4 rounded-2xl border border-ink/10 bg-white p-4"><p className="text-xs font-bold uppercase tracking-widest text-clay">Next upgrade</p><h3 className="font-display text-xl font-bold">{next.name}</h3><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Requirement label="Coins" owned={player.economy.coins} reserved={0} required={next.cost.coins}/><Requirement label="Wood" owned={player.inventory.wood} reserved={reserved.wood} required={next.cost.wood}/><Requirement label="Stone" owned={player.inventory.stone} reserved={reserved.stone} required={next.cost.stone}/>{'iron' in next.cost?<Requirement label="Iron" owned={player.inventory.iron} reserved={reserved.iron} required={next.cost.iron}/>:null}</div><p className="mt-3 text-xs text-ink/50">Reserved construction materials no longer occupy home storage.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><button disabled={!atHome||!canReserve||pending} onClick={()=>void fund(target)} className="rounded-xl border border-clay px-3 py-2.5 font-bold text-clay disabled:opacity-40">Reserve available materials</button><button disabled={!atHome||!hasRequirements||pending} onClick={()=>void upgrade(target)} className="flex items-center justify-center gap-2 rounded-xl bg-clay px-4 py-3 font-bold text-white disabled:opacity-40">{!atHome?<><LockKeyhole className="h-4 w-4"/>Walk Home</>:pending?'Working…':`Upgrade to ${next.name}`}</button></div></div>:<div className="mt-4 flex items-center gap-2 rounded-xl bg-moss/10 p-4 font-bold text-moss"><CheckCircle2/>Maximum property level reached</div>}</div></div></section>;
}

function Requirement({label,owned,reserved,required}:{label:string;owned:number;reserved:number;required:number}) { const met=owned+reserved>=required; return <div className={`rounded-lg p-2 ${met?'bg-moss/10':'bg-red-50'}`}><span className="text-ink/50">{label}</span><p className={met?'text-moss':'text-red-800'}><b>{owned+reserved}</b> / {required}</p>{reserved>0?<span className="text-[10px] text-ink/45">{reserved} reserved</span>:null}</div>; }
