-- Milestone 6 corrective/observability migration. No gameplay balances change.
alter table public.properties add column level_2_reached_at timestamptz;
alter table public.properties add column level_3_reached_at timestamptz;
create or replace function public.capture_property_progression() returns trigger language plpgsql security definer set search_path='' as $$begin if old.level<2 and new.level>=2 and new.level_2_reached_at is null then new.level_2_reached_at:=clock_timestamp();end if;if old.level<3 and new.level>=3 and new.level_3_reached_at is null then new.level_3_reached_at:=clock_timestamp();end if;return new;end$$;
create trigger capture_property_progression before update of level on public.properties for each row execute procedure public.capture_property_progression();

create table public.player_sessions(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,started_at timestamptz not null default clock_timestamp(),last_activity_at timestamptz not null default clock_timestamp(),ended_at timestamptz,observed_duration_seconds int generated always as(greatest(0,extract(epoch from(coalesce(ended_at,last_activity_at)-started_at))::int))stored);
alter table public.player_sessions enable row level security;create policy "read own sessions" on public.player_sessions for select using(player_id=auth.uid());revoke insert,update,delete on public.player_sessions from authenticated,anon;
create or replace function public.start_observed_session() returns uuid language plpgsql security definer set search_path='' as $$declare pid uuid:=auth.uid();sid uuid;begin if pid is null then raise exception 'AUTH_REQUIRED';end if;insert into public.player_sessions(player_id)values(pid)returning id into sid;return sid;end$$;
create or replace function public.heartbeat_observed_session(observed_session uuid) returns void language plpgsql security definer set search_path='' as $$begin update public.player_sessions set last_activity_at=clock_timestamp() where id=observed_session and player_id=auth.uid() and ended_at is null;if not found then raise exception 'SESSION_NOT_FOUND';end if;end$$;
create or replace function public.end_observed_session(observed_session uuid) returns void language plpgsql security definer set search_path='' as $$begin update public.player_sessions set last_activity_at=clock_timestamp(),ended_at=clock_timestamp() where id=observed_session and player_id=auth.uid() and ended_at is null;end$$;

alter table public.abuse_signals add column severity text not null default 'LOW' check(severity in('LOW','MEDIUM','HIGH'));
alter table public.abuse_signals add column first_seen_at timestamptz not null default now();
alter table public.abuse_signals add column last_seen_at timestamptz not null default now();
alter table public.abuse_signals add column occurrence_count int not null default 1;
alter table public.abuse_signals add column status text not null default 'OPEN' check(status in('OPEN','REVIEWED','DISMISSED'));
alter table public.abuse_signals add column reviewed_by uuid references public.profiles(id);
alter table public.abuse_signals add column internal_note text;
create or replace function public.require_admin() returns uuid language plpgsql security definer set search_path='' as $$declare pid uuid:=auth.uid();begin if pid is null or not exists(select 1 from public.profiles where id=pid and app_role='admin')then raise exception 'ADMIN_REQUIRED';end if;return pid;end$$;
create or replace function public.review_anomaly(anomaly_id bigint,next_status text,internal_note text default null) returns void language plpgsql security definer set search_path='' as $$declare admin_id uuid:=public.require_admin();begin if next_status not in('REVIEWED','DISMISSED')then raise exception 'INVALID_STATUS';end if;update public.abuse_signals set status=next_status,reviewed_by=admin_id,reviewed_at=clock_timestamp(),internal_note=left(internal_note,1000)where id=anomaly_id;if not found then raise exception 'ANOMALY_NOT_FOUND';end if;end$$;

create or replace function public.admin_inspect_player(target_player uuid) returns jsonb language plpgsql security definer set search_path='' as $$begin perform public.require_admin();return jsonb_build_object('profile',(select jsonb_build_object('id',p.id,'username',p.username,'createdAt',p.created_at)from public.profiles p where p.id=target_player),'resident',(select to_jsonb(r)-'player_id' from public.residents r where r.player_id=target_player),'economy',(select to_jsonb(e)-'player_id' from public.player_economy e where e.player_id=target_player),'inventory',(select jsonb_object_agg(resource,amount)from public.player_resources where player_id=target_player),'property',(select to_jsonb(pr)-'player_id' from public.properties pr where pr.player_id=target_player),'businesses',(select coalesce(jsonb_agg(to_jsonb(pb)),'[]')from public.player_businesses pb where pb.player_id=target_player),'skills',(select jsonb_object_agg(skill,xp)from public.player_skills where player_id=target_player),'season',(select to_jsonb(s)-'player_id' from public.player_season_progress s where s.player_id=target_player and season_id='season-0'),'ledger',(select coalesce(jsonb_agg(x),'[]')from(select * from public.economy_transactions where player_id=target_player order by created_at desc limit 30)x),'market',(select coalesce(jsonb_agg(x),'[]')from(select * from public.market_transactions where player_id=target_player order by created_at desc limit 20)x),'productions',(select coalesce(jsonb_agg(x),'[]')from(select * from public.business_productions where player_id=target_player order by started_at desc limit 20)x),'telemetry',(select coalesce(jsonb_agg(x),'[]')from(select * from public.action_telemetry where player_id=target_player order by occurred_at desc limit 50)x),'anomalies',(select coalesce(jsonb_agg(to_jsonb(a)),'[]')from public.abuse_signals a where a.player_id=target_player));end$$;

create or replace function public.get_admin_economy_dashboard_v2(period_days int default 1) returns jsonb language plpgsql security definer set search_path='' as $$
declare since timestamptz;created bigint;destroyed bigint;
begin perform public.require_admin();if period_days not in(1,7,30)then raise exception 'INVALID_PERIOD';end if;since:=date_trunc('day',clock_timestamp())-(period_days-1)*interval '1 day';select coalesce(sum(amount)filter(where resource='coins'and amount>0),0),coalesce(sum(-amount)filter(where resource='coins'and amount<0),0)into created,destroyed from public.economy_transactions where created_at>=since;
return jsonb_build_object('economyVersion',1,'periodDays',period_days,'economy',jsonb_build_object('coinsCreated',created,'coinsDestroyed',destroyed,'sourceSinkRatio',case when destroyed=0 then null else created::numeric/destroyed end,'marketplaceFees',(select coalesce(sum(fee),0)from public.market_transactions where created_at>=since),'businessTaxes',(select coalesce(sum(amount),0)from public.business_events where event_type='BUSINESS_TAX'and created_at>=since),'propertySpend',(select coalesce(sum(-amount),0)from public.economy_transactions where transaction_type='PROPERTY_UPGRADE_COIN_COST'and created_at>=since),'businessOpeningSpend',(select coalesce(sum(-amount),0)from public.economy_transactions where transaction_type='BUSINESS_OPEN_COST'and created_at>=since),'craftingSpend',(select coalesce(sum(-amount),0)from public.economy_transactions where transaction_type='CRAFT_COIN_COST'and created_at>=since)),
'resources',(select coalesce(jsonb_agg(jsonb_build_object('resource',resource,'created',created,'destroyed',destroyed,'net',created-destroyed)),'[]')from(select resource,sum(greatest(amount,0))created,sum(greatest(-amount,0))destroyed from public.economy_transactions where created_at>=since and resource::text in('wood','stone','iron','food','planks','meals','tools')group by resource)s),
'marketplace',(select jsonb_build_object('buyVolume',coalesce(sum(quantity)filter(where side='buy'),0),'sellVolume',coalesce(sum(quantity)filter(where side='sell'),0),'fees',coalesce(sum(fee),0),'resources',(select jsonb_agg(jsonb_build_object('resource',resource_id,'supply',current_supply,'price',public.calculate_market_unit_price(base_price,current_supply,initial_supply,min_multiplier,max_multiplier),'movement',current_supply-initial_supply))from public.market_resources))from public.market_transactions where created_at>=since),
'businesses',jsonb_build_object('distribution',(select coalesce(jsonb_object_agg(business_id,count),'{}')from(select business_id,count(*)count from public.player_businesses group by business_id)s),'productionStarts',(select count(*)from public.business_productions where started_at>=since),'productionClaims',(select count(*)from public.business_productions where claimed_at>=since),'readyUnclaimed',(select count(*)from public.business_productions where status='RUNNING'and ready_at<=clock_timestamp()),'tax',(select coalesce(sum(amount),0)from public.business_events where event_type='BUSINESS_TAX'and created_at>=since),'profitability',jsonb_build_object('generalStoreReference',jsonb_build_object('input',98,'net',71,'profit',-27,'profitPerHour',-108),'restaurantReference',jsonb_build_object('input',64,'output',120,'profit',56,'profitPerHour',168),'workshopReference',jsonb_build_object('input',184,'output',160,'profit',-24,'profitPerHour',-48))),
'property',jsonb_build_object('distribution',(select jsonb_object_agg(level,count)from(select level,count(*)count from public.properties group by level)s),'constructionReservations',(select count(*)from public.property_upgrade_progress),'averageStorageUsage',(select avg(public.effective_storage_used(player_id)::numeric/nullif(storage_capacity,0))from public.properties),'storageFullRate',(select avg((public.effective_storage_used(player_id)>=storage_capacity)::int::numeric)from public.properties),'averageHoursToLevel2',(select avg(extract(epoch from(pr.level_2_reached_at-p.created_at))/3600)from public.properties pr join public.profiles p on p.id=pr.player_id where pr.level_2_reached_at is not null),'averageHoursLevel2To3',(select avg(extract(epoch from(level_3_reached_at-level_2_reached_at))/3600)from public.properties where level_2_reached_at is not null and level_3_reached_at is not null)),
'season',jsonb_build_object('averageFp',(select avg(amount)from public.founder_point_history where created_at>=since),'weeklyClaims',(select count(*)from public.founder_point_history where reason='WEEKLY_STREAK'and created_at>=since),'achievementClaims',(select count(*)from public.achievement_claims where claimed_at>=since),'tiers',(select jsonb_build_object('Citizen',count(*)filter(where founder_points>=500 and founder_points<1200),'Whitelist',count(*)filter(where founder_points>=1200 and founder_points<2000),'Priority',count(*)filter(where founder_points>=2000 and founder_points<3000),'Guaranteed',count(*)filter(where founder_points>=3000))from public.player_season_progress where season_id='season-0')),
'activity',jsonb_build_object('activePlayers',(select count(distinct player_id)from public.action_telemetry where success and occurred_at>=since),'jobs',(select count(*)from public.action_telemetry where event_type in('JOB_COMPLETE','JOB_REWARD')and occurred_at>=since),'crafts',(select count(*)from public.action_telemetry where event_type='CRAFT_COMPLETE'and occurred_at>=since),'trades',(select count(*)from public.market_transactions where created_at>=since),'orders',(select count(*)from public.player_orders where completed_at>=since),'productions',(select count(*)from public.business_productions where claimed_at>=since),'approximateSessionMinutes',(select coalesce(sum(observed_duration_seconds),0)/60 from public.player_sessions where started_at>=since)),
'retention',jsonb_build_object('definition','created-day cohort with meaningful action on exact target day; suppress rates below 5 accounts','d1',null,'d7',null,'d14',null),
'funnel',(select jsonb_agg(x)from(values('Account Created',(select count(*)from public.profiles)),('First Job',(select count(*)from public.residents where jobs_completed>0)),('First Craft',(select count(distinct player_id)from public.economy_transactions where transaction_type='CRAFT_OUTPUT')),('First NPC Order',(select count(distinct player_id)from public.player_orders)),('First Market Trade',(select count(distinct player_id)from public.market_transactions)),('Property Level 2',(select count(*)from public.properties where level>=2)),('First Business',(select count(distinct player_id)from public.player_businesses)),('First Production Claim',(select count(distinct player_id)from public.business_productions where claimed_at is not null)),('Citizen',(select count(*)from public.player_season_progress where founder_points>=500)),('Whitelist',(select count(*)from public.player_season_progress where founder_points>=1200)))x(stage,count)),
'anomalies',(select coalesce(jsonb_agg(to_jsonb(a)order by severity desc,last_seen_at desc),'[]')from public.abuse_signals a where status='OPEN'),'configuration',jsonb_build_object('version',1,'marketFee',.05,'businessTax',.05,'dailyFpCap',45,'fpThresholds',jsonb_build_array(500,1200,2000,3000),'productionMinutes',jsonb_build_object('generalStore',15,'restaurant',20,'workshop',30)));
end$$;

create or replace function public.telemetry_from_ledger() returns trigger language plpgsql security definer set search_path='' as $$declare event_name text;begin event_name:=case when new.transaction_type like 'JOB%'then'JOB_COMPLETE'when new.transaction_type='CRAFT_OUTPUT'then'CRAFT_COMPLETE'when new.transaction_type='MEAL_CONSUME'then'MEAL_CONSUME'when new.transaction_type='PROPERTY_LEVEL_CHANGE'then'PROPERTY_UPGRADE'when new.transaction_type='PROPERTY_UPGRADE_RESERVE'then'PROPERTY_RESERVE'when new.transaction_type='BUSINESS_OPEN_COST'then'BUSINESS_OPEN'when new.transaction_type='BUSINESS_OUTPUT_RESOURCE'or new.transaction_type='BUSINESS_NET_REVENUE'then'BUSINESS_PRODUCTION_CLAIM'else null end;if event_name is not null and not exists(select 1 from public.action_telemetry where player_id=new.player_id and event_type=event_name and metadata->>'referenceId'=new.reference_id::text)then insert into public.action_telemetry(player_id,event_type,metadata)values(new.player_id,event_name,jsonb_build_object('referenceId',new.reference_id));end if;return new;end$$;
create trigger economy_ledger_action_telemetry after insert on public.economy_transactions for each row execute procedure public.telemetry_from_ledger();

revoke execute on function public.require_admin(),public.get_admin_economy_dashboard_v2(int),public.admin_inspect_player(uuid),public.review_anomaly(bigint,text,text)from public,anon;
grant execute on function public.get_admin_economy_dashboard_v2(int),public.admin_inspect_player(uuid),public.review_anomaly(bigint,text,text),public.start_observed_session(),public.heartbeat_observed_session(uuid),public.end_observed_session(uuid)to authenticated;
