-- Milestone 7 additive runtime correction.
-- Supabase local migrations cannot ALTER FUNCTION SET plpgsql.variable_conflict,
-- so replace the affected functions with body-local PL/pgSQL conflict policy.

create or replace function public.open_business(requested_business_type text,request_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare pid uuid:=auth.uid(); cost int; slots int; used int; coins_before bigint; ref uuid:=gen_random_uuid(); result jsonb; old_action text; business_row uuid; action_name text:='open_business:'||requested_business_type;
begin
 if pid is null then raise exception 'Authentication required'; end if; if requested_business_type not in('general_store','restaurant','workshop') then raise exception 'Unsupported business type'; end if;
 cost:=case requested_business_type when 'general_store' then 600 when 'restaurant' then 700 else 900 end;
 perform pg_advisory_xact_lock(hashtextextended(pid::text,41)); select ar.action,ar.result into old_action,result from public.action_requests ar where ar.player_id=pid and ar.idempotency_key=request_key; if found then if old_action<>action_name then raise exception 'Idempotency key already used for another action'; end if; return result; end if;
 select business_slots into slots from public.properties where player_id=pid for update; select count(*) into used from public.player_businesses where player_id=pid and status='ACTIVE'; if used>=slots then raise exception 'No business slot available'; end if; if exists(select 1 from public.player_businesses where player_id=pid and business_id=requested_business_type) then raise exception 'Business type already owned'; end if;
 select coins into coins_before from public.player_economy where player_id=pid for update; if coins_before<cost then raise exception 'Not enough coins'; end if;
 insert into public.action_requests values(pid,request_key,action_name,null,now()); update public.player_economy set coins=coins-cost where player_id=pid; insert into public.player_businesses(player_id,business_id,status,property_player_id) values(pid,requested_business_type,'ACTIVE',pid) returning id into business_row;
 insert into public.economy_transactions(player_id,transaction_type,resource,amount,balance_before,balance_after,reference_id) values(pid,'BUSINESS_OPEN_COST','coins',-cost,coins_before,coins_before-cost,ref);
 result:=jsonb_build_object('state',public.get_player_game_state(pid),'message','Business opened','transactionId',ref); update public.action_requests set result=result where player_id=pid and idempotency_key=request_key; return result;
end $$;

create or replace function public.assign_resident_to_business(requested_resident uuid,requested_business uuid,request_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare pid uuid:=auth.uid(); result jsonb; old_action text; state text; action_name text:='assign_business:'||requested_business;
begin
 if pid is null then raise exception 'Authentication required'; end if; perform pg_advisory_xact_lock(hashtextextended(pid::text,42)); select ar.action,ar.result into old_action,result from public.action_requests ar where ar.player_id=pid and ar.idempotency_key=request_key; if found then if old_action<>action_name then raise exception 'Idempotency key already used for another action'; end if; return result; end if;
 select work_state into state from public.residents where id=requested_resident and player_id=pid for update; if state is null then raise exception 'Resident not owned'; end if; if state='PRODUCING' then raise exception 'Resident is producing'; end if; if exists(select 1 from public.player_businesses where assigned_resident_id=requested_resident) then raise exception 'Resident already assigned'; end if;
 perform 1 from public.player_businesses where id=requested_business and player_id=pid and assigned_resident_id is null for update; if not found then raise exception 'Business unavailable or already assigned'; end if;
 insert into public.action_requests values(pid,request_key,action_name,null,now()); update public.player_businesses set assigned_resident_id=requested_resident where id=requested_business; update public.residents set assigned_business_id=requested_business,work_state='ASSIGNED_BUSINESS' where id=requested_resident;
 result:=jsonb_build_object('state',public.get_player_game_state(pid),'message','Resident assigned'); update public.action_requests set result=result where player_id=pid and idempotency_key=request_key; return result;
end $$;

create or replace function public.unassign_resident_from_business(requested_resident uuid,requested_business uuid,request_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare pid uuid:=auth.uid(); result jsonb; old_action text; action_name text:='unassign_business:'||requested_business;
begin
 if pid is null then raise exception 'Authentication required'; end if; perform pg_advisory_xact_lock(hashtextextended(pid::text,43)); select ar.action,ar.result into old_action,result from public.action_requests ar where ar.player_id=pid and ar.idempotency_key=request_key; if found then if old_action<>action_name then raise exception 'Idempotency key already used for another action'; end if; return result; end if;
 perform 1 from public.player_businesses pb join public.residents r on r.id=pb.assigned_resident_id where pb.id=requested_business and pb.player_id=pid and r.id=requested_resident for update of pb,r; if not found then raise exception 'Assignment not found'; end if; if exists(select 1 from public.business_productions where business_id=requested_business and status='RUNNING') then raise exception 'PRODUCTION_ACTIVE'; end if;
 insert into public.action_requests values(pid,request_key,action_name,null,now()); update public.player_businesses set assigned_resident_id=null where id=requested_business; update public.residents set assigned_business_id=null,work_state='IDLE' where id=requested_resident;
 result:=jsonb_build_object('state',public.get_player_game_state(pid),'message','Resident unassigned'); update public.action_requests set result=result where player_id=pid and idempotency_key=request_key; return result;
end $$;

create or replace function public.start_business_production(requested_business uuid,requested_recipe text,request_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare pid uuid:=auth.uid(); btype text; resident uuid; state text; duration interval; reserve_units int; first_resource text; first_amount int; second_resource text; second_amount int; before_first int; before_second int; capacity int; ref uuid:=gen_random_uuid(); production uuid; result jsonb; old_action text; action_name text:='start_production:'||requested_business||':'||requested_recipe;
begin
 if pid is null then raise exception 'Authentication required'; end if; perform pg_advisory_xact_lock(hashtextextended(pid::text,44)); select ar.action,ar.result into old_action,result from public.action_requests ar where ar.player_id=pid and ar.idempotency_key=request_key; if found then if old_action<>action_name then raise exception 'Idempotency key already used for another action'; end if; return result; end if;
 select business_id,assigned_resident_id into btype,resident from public.player_businesses where id=requested_business and player_id=pid and status='ACTIVE' for update; if btype is null then raise exception 'Business not owned'; end if; if resident is null then raise exception 'Resident required'; end if;
 if (btype='general_store' and requested_recipe<>'general_store_sales') or (btype='restaurant' and requested_recipe<>'restaurant_meals') or (btype='workshop' and requested_recipe<>'workshop_tools') then raise exception 'Recipe does not belong to business'; end if;
 select work_state into state from public.residents where id=resident and player_id=pid for update; if state='PRODUCING' then raise exception 'Resident already producing'; end if; if exists(select 1 from public.business_productions where business_id=requested_business and status='RUNNING') then raise exception 'Production already active'; end if;
 if btype='general_store' then duration:=interval '15 minutes'; reserve_units:=0; first_resource:='wood';first_amount:=3;second_resource:='food';second_amount:=2; elsif btype='restaurant' then duration:=interval '20 minutes';reserve_units:=2;first_resource:='food';first_amount:=4; else duration:=interval '30 minutes';reserve_units:=1;first_resource:='wood';first_amount:=4;second_resource:='iron';second_amount:=2; end if;
 select storage_capacity into capacity from public.properties where player_id=pid for update; if public.effective_storage_used(pid)+reserve_units>capacity then raise exception 'Storage capacity exceeded'; end if;
 select amount into before_first from public.player_resources where player_id=pid and resource=first_resource for update; if before_first<first_amount then raise exception 'Not enough %',first_resource; end if; if second_resource is not null then select amount into before_second from public.player_resources where player_id=pid and resource=second_resource for update; if before_second<second_amount then raise exception 'Not enough %',second_resource; end if; end if;
 insert into public.action_requests values(pid,request_key,action_name,null,now()); update public.player_resources set amount=amount-first_amount where player_id=pid and resource=first_resource; if second_resource is not null then update public.player_resources set amount=amount-second_amount where player_id=pid and resource=second_resource; end if;
 insert into public.business_productions(player_id,business_id,resident_id,recipe_id,started_at,ready_at,reference_id) values(pid,requested_business,resident,requested_recipe,clock_timestamp(),clock_timestamp()+duration,ref) returning id into production;
 if reserve_units>0 then insert into public.production_output_reservations values(production,pid,reserve_units,case when btype='restaurant' then 'meals' else 'tools' end,now()); end if; update public.residents set work_state='PRODUCING' where id=resident;
 insert into public.economy_transactions(player_id,transaction_type,resource,amount,balance_before,balance_after,reference_id) values(pid,'BUSINESS_INPUT_RESOURCE',first_resource::public.resource_kind,-first_amount,before_first,before_first-first_amount,ref); if second_resource is not null then insert into public.economy_transactions(player_id,transaction_type,resource,amount,balance_before,balance_after,reference_id) values(pid,'BUSINESS_INPUT_RESOURCE',second_resource::public.resource_kind,-second_amount,before_second,before_second-second_amount,ref); end if;
 result:=jsonb_build_object('state',public.get_player_game_state(pid),'message','Production started','transactionId',ref); update public.action_requests set result=result where player_id=pid and idempotency_key=request_key; return result;
end $$;

create or replace function public.claim_business_production(requested_production uuid,request_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare pid uuid:=auth.uid(); row_data public.business_productions%rowtype; btype text; output_resource text; output_amount int; output_before int; coins_before bigint; gross int:=0; tax int:=0; net int:=0; profession text; profession_before int; xp_reward int; xp_before int; ref uuid:=gen_random_uuid(); result jsonb; old_action text; action_name text:='claim_production:'||requested_production;
begin
 if pid is null then raise exception 'Authentication required'; end if; perform pg_advisory_xact_lock(hashtextextended(pid::text,45)); select ar.action,ar.result into old_action,result from public.action_requests ar where ar.player_id=pid and ar.idempotency_key=request_key; if found then if old_action<>action_name then raise exception 'Idempotency key already used for another action'; end if; return result; end if;
 select * into row_data from public.business_productions where id=requested_production and player_id=pid for update; if not found then raise exception 'Production not found'; end if; if row_data.status='CLAIMED' then raise exception 'Production already claimed'; end if; if clock_timestamp()<row_data.ready_at then raise exception 'PRODUCTION_NOT_READY ready_at=%',row_data.ready_at; end if;
 select business_id into btype from public.player_businesses where id=row_data.business_id and player_id=pid for update; if btype='general_store' then gross:=75;tax:=ceil(gross*.05);net:=gross-tax;profession:='merchant';xp_reward:=10; elsif btype='restaurant' then output_resource:='meals';output_amount:=2;profession:='chef';xp_reward:=12; else output_resource:='tools';output_amount:=1;profession:='engineer';xp_reward:=15; end if;
 select xp into xp_before from public.residents where id=row_data.resident_id for update; select xp into profession_before from public.player_skills where player_id=pid and skill=profession for update; insert into public.action_requests values(pid,request_key,action_name,null,now());
 if btype='general_store' then select coins into coins_before from public.player_economy where player_id=pid for update; update public.player_economy set coins=coins+net where player_id=pid; update public.business_tax_totals set coins_removed=coins_removed+tax,updated_at=now() where id; update public.business_productions set gross_coins=gross,tax_coins=tax,net_coins=net where id=requested_production; insert into public.economy_transactions(player_id,transaction_type,resource,amount,balance_before,balance_after,reference_id) values(pid,'BUSINESS_NET_REVENUE','coins',net,coins_before,coins_before+net,ref); insert into public.business_events(player_id,production_id,event_type,amount,reference_id) values(pid,requested_production,'BUSINESS_GROSS_REVENUE',gross,ref),(pid,requested_production,'BUSINESS_TAX',tax,ref); else select amount into output_before from public.player_resources where player_id=pid and resource=output_resource for update; delete from public.production_output_reservations where production_id=requested_production; update public.player_resources set amount=amount+output_amount where player_id=pid and resource=output_resource; insert into public.economy_transactions(player_id,transaction_type,resource,amount,balance_before,balance_after,reference_id) values(pid,'BUSINESS_OUTPUT_RESOURCE',output_resource::public.resource_kind,output_amount,output_before,output_before+output_amount,ref); end if;
 update public.residents set xp=xp+xp_reward,level=1+((xp+xp_reward)/100),work_state='ASSIGNED_BUSINESS' where id=row_data.resident_id; update public.player_skills set xp=xp+12 where player_id=pid and skill=profession; update public.business_productions set status='CLAIMED',claimed_at=clock_timestamp() where id=requested_production;
 insert into public.player_quests(player_id,quest_id,progress,quest_date) values(pid,'daily-business-1',1,current_date) on conflict(player_id,quest_id,quest_date) do update set progress=greatest(public.player_quests.progress,1);
 result:=jsonb_build_object('state',public.get_player_game_state(pid),'message','Production claimed','transactionId',ref); update public.action_requests set result=result where player_id=pid and idempotency_key=request_key; return result;
end $$;

create or replace function public.get_admin_economy_dashboard_v2(period_days int default 1) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column
declare since timestamptz;created bigint;destroyed bigint;
begin perform public.require_admin();if period_days not in(1,7,30)then raise exception 'INVALID_PERIOD';end if;since:=date_trunc('day',clock_timestamp())-(period_days-1)*interval '1 day';select coalesce(sum(amount)filter(where resource='coins'and amount>0),0),coalesce(sum(-amount)filter(where resource='coins'and amount<0),0)into created,destroyed from public.economy_transactions where created_at>=since;
return jsonb_build_object('economyVersion',1,'periodDays',period_days,'economy',jsonb_build_object('coinsCreated',created,'coinsDestroyed',destroyed,'sourceSinkRatio',case when destroyed=0 then null else created::numeric/destroyed end,'marketplaceFees',(select coalesce(sum(fee),0)from public.market_transactions where created_at>=since),'businessTaxes',(select coalesce(sum(amount),0)from public.business_events where event_type='BUSINESS_TAX'and created_at>=since),'propertySpend',(select coalesce(sum(-amount),0)from public.economy_transactions where transaction_type='PROPERTY_UPGRADE_COIN_COST'and created_at>=since),'businessOpeningSpend',(select coalesce(sum(-amount),0)from public.economy_transactions where transaction_type='BUSINESS_OPEN_COST'and created_at>=since),'craftingSpend',(select coalesce(sum(-amount),0)from public.economy_transactions where transaction_type='CRAFT_COIN_COST'and created_at>=since)),
'resources',(select coalesce(jsonb_agg(jsonb_build_object('resource',resource,'created',created,'destroyed',destroyed,'net',created-destroyed)),'[]')from(select resource,sum(greatest(amount,0))created,sum(greatest(-amount,0))destroyed from public.economy_transactions where created_at>=since and resource::text in('wood','stone','iron','food','planks','meals','tools')group by resource)s),
'marketplace',(select jsonb_build_object('buyVolume',coalesce(sum(quantity)filter(where side='buy'),0),'sellVolume',coalesce(sum(quantity)filter(where side='sell'),0),'fees',coalesce(sum(fee),0),'resources',(select jsonb_agg(jsonb_build_object('resource',resource_id,'supply',current_supply,'price',public.calculate_market_unit_price(base_price,current_supply,initial_supply,min_multiplier,max_multiplier),'movement',current_supply-initial_supply))from public.market_resources))from public.market_transactions where created_at>=since),
'businesses',jsonb_build_object('distribution',(select coalesce(jsonb_object_agg(business_id,count),'{}')from(select business_id,count(*)count from public.player_businesses group by business_id)s),'productionStarts',(select count(*)from public.business_productions where started_at>=since),'productionClaims',(select count(*)from public.business_productions where claimed_at>=since),'readyUnclaimed',(select count(*)from public.business_productions where status='RUNNING'and ready_at<=clock_timestamp()),'tax',(select coalesce(sum(amount),0)from public.business_events where event_type='BUSINESS_TAX'and created_at>=since),'profitability',jsonb_build_object('generalStoreReference',jsonb_build_object('input',98,'net',71,'profit',-27,'profitPerHour',-108),'restaurantReference',jsonb_build_object('input',64,'output',120,'profit',56,'profitPerHour',168),'workshopReference',jsonb_build_object('input',184,'output',160,'profit',-24,'profitPerHour',-48))),
'property',jsonb_build_object('distribution',(select jsonb_object_agg(level,count)from(select level,count(*)count from public.properties group by level)s),'constructionReservations',(select count(*)from public.property_upgrade_progress),'averageStorageUsage',(select avg(public.effective_storage_used(player_id)::numeric/nullif(storage_capacity,0))from public.properties),'storageFullRate',(select avg((public.effective_storage_used(player_id)>=storage_capacity)::int::numeric)from public.properties),'averageHoursToLevel2',(select avg(extract(epoch from(pr.level_2_reached_at-p.created_at))/3600)from public.properties pr join public.profiles p on p.id=pr.player_id where pr.level_2_reached_at is not null),'averageHoursLevel2To3',(select avg(extract(epoch from(level_3_reached_at-level_2_reached_at))/3600)from public.properties where level_2_reached_at is not null and level_3_reached_at is not null)),
'season',jsonb_build_object('averageFp',(select avg(amount)from public.founder_point_history where created_at>=since),'weeklyClaims',(select count(*)from public.founder_point_history where reason='WEEKLY_STREAK'and created_at>=since),'achievementClaims',(select count(*)from public.achievement_claims where claimed_at>=since),'tiers',(select jsonb_build_object('Citizen',count(*)filter(where founder_points>=500 and founder_points<1200),'Whitelist',count(*)filter(where founder_points>=1200 and founder_points<2000),'Priority',count(*)filter(where founder_points>=2000 and founder_points<3000),'Guaranteed',count(*)filter(where founder_points>=3000))from public.player_season_progress where season_id='season-0')),
'activity',jsonb_build_object('activePlayers',(select count(distinct player_id)from public.action_telemetry where success and occurred_at>=since),'jobs',(select count(*)from public.action_telemetry where event_type in('JOB_COMPLETE','JOB_REWARD')and occurred_at>=since),'crafts',(select count(*)from public.action_telemetry where event_type='CRAFT_COMPLETE'and occurred_at>=since),'trades',(select count(*)from public.market_transactions where created_at>=since),'orders',(select count(*)from public.player_orders where completed_at>=since),'productions',(select count(*)from public.business_productions where claimed_at>=since),'approximateSessionMinutes',(select coalesce(sum(observed_duration_seconds),0)/60 from public.player_sessions where started_at>=since)),
'retention',jsonb_build_object('definition','created-day cohort with meaningful action on exact target day; suppress rates below 5 accounts','d1',null,'d7',null,'d14',null),
'funnel',(select jsonb_agg(x)from(values('Account Created',(select count(*)from public.profiles)),('First Job',(select count(*)from public.residents where jobs_completed>0)),('First Craft',(select count(distinct player_id)from public.economy_transactions where transaction_type='CRAFT_OUTPUT')),('First NPC Order',(select count(distinct player_id)from public.player_orders)),('First Market Trade',(select count(distinct player_id)from public.market_transactions)),('Property Level 2',(select count(*)from public.properties where level>=2)),('First Business',(select count(distinct player_id)from public.player_businesses)),('First Production Claim',(select count(distinct player_id)from public.business_productions where claimed_at is not null)),('Citizen',(select count(*)from public.player_season_progress where founder_points>=500)),('Whitelist',(select count(*)from public.player_season_progress where founder_points>=1200)))x(stage,count)),
'anomalies',(select coalesce(jsonb_agg(to_jsonb(a)order by severity desc,last_seen_at desc),'[]')from public.abuse_signals a where status='OPEN'),'configuration',jsonb_build_object('version',1,'marketFee',.05,'businessTax',.05,'dailyFpCap',45,'fpThresholds',jsonb_build_array(500,1200,2000,3000),'productionMinutes',jsonb_build_object('generalStore',15,'restaurant',20,'workshop',30)));
end$$;

revoke execute on function public.open_business(text,uuid),public.assign_resident_to_business(uuid,uuid,uuid),public.unassign_resident_from_business(uuid,uuid,uuid),public.start_business_production(uuid,text,uuid),public.claim_business_production(uuid,uuid),public.get_admin_economy_dashboard_v2(int) from public,anon;
grant execute on function public.open_business(text,uuid),public.assign_resident_to_business(uuid,uuid,uuid),public.unassign_resident_from_business(uuid,uuid,uuid),public.start_business_production(uuid,text,uuid),public.claim_business_production(uuid,uuid),public.get_admin_economy_dashboard_v2(int) to authenticated;
