import { useState } from 'react';
import { LoaderCircle, WalletCards, X } from 'lucide-react';
import { connectWallet, GAME_CHAIN_ID, shortWallet, signInWithWallet, switchToGameChain, type EthereumProvider } from '../../services/walletAuth';

export function WalletAuthPanel({onClose}:{onClose:()=>void}){
 const[address,setAddress]=useState<string|null>(null);const[provider,setProvider]=useState<EthereumProvider|null>(null);const[chainId,setChainId]=useState<number|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 async function connect(){setBusy(true);setMessage('');try{const connected=await connectWallet();setProvider(connected.provider);setAddress(connected.address);setChainId(connected.chainId);}catch(error){setMessage(error instanceof Error?error.message:'Wallet connection failed.');}finally{setBusy(false)}}
 async function switchChain(){if(!provider)return;setBusy(true);setMessage('');try{await switchToGameChain(provider);setChainId(GAME_CHAIN_ID);}catch(error){setMessage(error instanceof Error?error.message:'Network switch failed.');}finally{setBusy(false)}}
 async function verify(){if(!provider||!address||chainId!==GAME_CHAIN_ID)return;setBusy(true);setMessage('');try{await signInWithWallet(provider,address);}catch(error){setMessage(error instanceof Error?error.message:'Wallet authentication failed.');}finally{setBusy(false)}}
 return <main className="min-h-dvh bg-ink p-4 text-cream sm:grid sm:place-items-center"><section className="relative mx-auto w-full max-w-lg rounded-3xl bg-cream p-7 text-center text-ink shadow-2xl"><button onClick={onClose} className="absolute right-3 top-3 rounded-full p-2 hover:bg-ink/10" aria-label="Close wallet authentication"><X className="h-5 w-5"/></button><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-moss text-white"><WalletCards/></span><p className="mt-5 text-xs font-bold uppercase tracking-[.25em] text-clay">Block City Citizen</p><h2 className="mt-2 font-display text-3xl font-bold">Verify your citizenship</h2><p className="mt-3 text-sm text-ink/60">Connect your wallet and sign a zero-gas message. NFT ownership is verified securely by the Block City server.</p>{address?<div className="mt-5 rounded-xl bg-white p-4"><p className="text-xs uppercase tracking-widest text-ink/45">Wallet</p><p className="mt-1 font-mono font-bold">{shortWallet(address)}</p></div>:null}{message?<p role="alert" className="mt-4 rounded-xl bg-amber-100 p-3 text-sm text-amber-900">{message}</p>:null}{!address?<button disabled={busy} onClick={()=>void connect()} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-moss px-4 py-3 font-bold text-white disabled:opacity-50">{busy?<LoaderCircle className="h-4 w-4 animate-spin"/>:null}Connect Wallet</button>:chainId!==GAME_CHAIN_ID?<button disabled={busy} onClick={()=>void switchChain()} className="mt-6 w-full rounded-xl bg-clay px-4 py-3 font-bold text-white disabled:opacity-50">Switch to Robinhood Chain</button>:<button disabled={busy} onClick={()=>void verify()} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-moss px-4 py-3 font-bold text-white disabled:opacity-50">{busy?<LoaderCircle className="h-4 w-4 animate-spin"/>:null}Sign to Verify</button>}</section></main>;
}
